Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: localhost:8000/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  DefaultContextTimeout: 60
Database:
  DBType: mysql
  Username: shou
  Password: password
  Host: localhost:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: test-secret
  Issuer: blog-service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxx
  Password: xxx
  IsSSL: true
  From: xxx
  To:
    - xxx
